#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

/* Headers for the Cif to C translation of Amigo.cif
 * Generated file, DO NOT EDIT
 */
typedef _Bool BoolType;
typedef int32_t IntType;
typedef double RealType;

/* Types of the specification.
 * Note that integer ranges are ignored in C.
 */
enum EnumAmigo_ {
    _Amigo_completing,
    _Amigo_grabbing,
    _Amigo_idle,
    _Amigo_idling,
    _Amigo_moving,
    _Amigo_moving_to,
    _Amigo_phase1,
    _Amigo_phase2,
    _Amigo_planning,
    _Amigo_planning_to_grab,
    _Amigo_replanning,
    _Amigo_starting,
    _Amigo_wait,
    _Amigo_X,
};
typedef enum EnumAmigo_ AmigoEnum;

extern const char *enum_names[];
extern int EnumTypePrint(AmigoEnum value, char *dest, int start, int end);


/* Event declarations. */
enum AmigoEventEnum_ {
    EVT_INITIAL_,                   /**< Initial step. */
    EVT_DELAY_,                     /**< Delay step. */
    EVT_TAU_,                       /**< Tau step. */
    goto_phase2_,                   /**< Event goto_phase2. */
    arm_left_idle_,                 /**< Event arm_left_idle. */
    arm_left_move_,                 /**< Event arm_left_move. */
    arm_left_plan_,                 /**< Event arm_left_plan. */
    arm_left_replan_,               /**< Event arm_left_replan. */
    arm_left_plan_to_grab_,         /**< Event arm_left_plan_to_grab. */
    arm_left_grab_,                 /**< Event arm_left_grab. */
    arm_right_idle_,                /**< Event arm_right_idle. */
    arm_right_move_,                /**< Event arm_right_move. */
    arm_right_plan_,                /**< Event arm_right_plan. */
    arm_right_replan_,              /**< Event arm_right_replan. */
    arm_right_plan_to_grab_,        /**< Event arm_right_plan_to_grab. */
    arm_right_grab_,                /**< Event arm_right_grab. */
    base_idle_,                     /**< Event base_idle. */
    base_move_,                     /**< Event base_move. */
    base_plan_,                     /**< Event base_plan. */
    grab_skill_grab_,               /**< Event grab_skill_grab. */
    grab_skill_determine_grab_arm_, /**< Event grab_skill_determine_grab_arm. */
    left_grab_exec_check_in_WS_,    /**< Event left_grab_exec_check_in_WS. */
    left_grab_exec_start_,          /**< Event left_grab_exec_start. */
    left_grab_exec_complete_,       /**< Event left_grab_exec_complete. */
    left_grab_exec_idle_,           /**< Event left_grab_exec_idle. */
    navigation_skill_move_to_,      /**< Event navigation_skill_move_to. */
    right_grab_exec_check_in_WS_,   /**< Event right_grab_exec_check_in_WS. */
    right_grab_exec_start_,         /**< Event right_grab_exec_start. */
    right_grab_exec_complete_,      /**< Event right_grab_exec_complete. */
    right_grab_exec_idle_,          /**< Event right_grab_exec_idle. */
    task_waiting_,                  /**< Event task_waiting. */
};
typedef enum AmigoEventEnum_ Amigo_Event_;

/** Names of all the events. */
extern const char *Amigo_event_names[];

/* Constants. */


/* Input variables. */
extern IntType arm_left_plan_viable_;         /**< Input variable "int[0..2] arm_left.plan_viable". */
extern BoolType arm_left_collision_on_path_;  /**< Input variable "bool arm_left.collision_on_path". */
extern BoolType arm_left_moving_arm_;         /**< Input variable "bool arm_left.moving_arm". */
extern BoolType arm_left_goal_reached_;       /**< Input variable "bool arm_left.goal_reached". */
extern BoolType arm_left_object_in_arm_;      /**< Input variable "bool arm_left.object_in_arm". */
extern IntType arm_right_plan_viable_;        /**< Input variable "int[0..2] arm_right.plan_viable". */
extern BoolType arm_right_collision_on_path_; /**< Input variable "bool arm_right.collision_on_path". */
extern BoolType arm_right_moving_arm_;        /**< Input variable "bool arm_right.moving_arm". */
extern BoolType arm_right_goal_reached_;      /**< Input variable "bool arm_right.goal_reached". */
extern BoolType arm_right_object_in_arm_;     /**< Input variable "bool arm_right.object_in_arm". */
extern IntType base_plan_viable_;             /**< Input variable "int[0..2] base.plan_viable". */
extern BoolType base_collision_on_path_;      /**< Input variable "bool base.collision_on_path". */
extern BoolType base_moving_base_;            /**< Input variable "bool base.moving_base". */
extern BoolType base_goal_reached_;           /**< Input variable "bool base.goal_reached". */
extern IntType grab_skill_use_arm_;           /**< Input variable "int[0..2] grab_skill.use_arm". */
extern IntType left_grab_exec_object_in_WS_;  /**< Input variable "int[0..2] left_grab_exec.object_in_WS". */
extern IntType right_grab_exec_object_in_WS_; /**< Input variable "int[0..2] right_grab_exec.object_in_WS". */
extern BoolType task_object_grabbed_;         /**< Input variable "bool task.object_grabbed". */

// extern void Amigo_AssignInputVariables();

/* Declaration of internal functions. */


/* State variables (use for output only). */
extern RealType model_time; /**< Current model time. */
extern AmigoEnum arm_left_;              /**< Discrete variable "E arm_left". */
extern AmigoEnum arm_right_;             /**< Discrete variable "E arm_right". */
extern AmigoEnum base_;                  /**< Discrete variable "E base". */
extern AmigoEnum grab_skill_;            /**< Discrete variable "E grab_skill". */
extern AmigoEnum left_grab_exec_;        /**< Discrete variable "E left_grab_exec". */
extern AmigoEnum navigation_skill_;      /**< Discrete variable "E navigation_skill". */
extern AmigoEnum requirement_arm_left_;  /**< Discrete variable "E requirement_arm_left". */
extern AmigoEnum requirement_arm_right_; /**< Discrete variable "E requirement_arm_right". */
extern AmigoEnum right_grab_exec_;       /**< Discrete variable "E right_grab_exec". */
extern AmigoEnum SafeBaseMovement_;      /**< Discrete variable "E SafeBaseMovement". */
extern AmigoEnum sup_;                   /**< Discrete variable "E sup". */
extern BoolType task_navigating_;        /**< Discrete variable "bool task.navigating". */
extern BoolType task_grabbing_;          /**< Discrete variable "bool task.grabbing". */
extern AmigoEnum task_;                  /**< Discrete variable "E task". */

/* Algebraic and derivative functions (use for output only). */






/* Code entry points. */
void Amigo_EngineFirstStep(void);
void Amigo_EngineTimeStep(double delta);

// #if EVENT_OUTPUT
// /**
//  * External callback function reporting about the execution of an event.
//  * @param event Event veing executed.
//  * @param pre If \c TRUE, event is about to be executed. If \c FALSE, event has been executed.
//  * @note Function must be implemented externally.
//  */
// extern void Amigo_InfoEvent(Amigo_Event_ event, BoolType pre);
// #endif

// #if PRINT_OUTPUT
// /**
//  * External callback function to output the given text-line to the given filename.
//  * @param text Text to print (does not have a EOL character).
//  * @param fname Name of the file to print to.
//  */
// extern void Amigo_PrintOutput(const char *text, const char *fname);
// #endif

// #endif

/* Cif to C translation of Amigo.cif
 * Generated file, DO NOT EDIT
 */

#include <stdio.h>
#include <stdlib.h>
// #include "Amigo_engine.h"
#include "Amigo_library.h"


#ifndef MAX_NUM_EVENTS
#define MAX_NUM_EVENTS 30
#endif

#ifndef EVENT_OUTPUT
#define EVENT_OUTPUT 1
#endif
/* What to do if a range error is found in an assignment? */
#ifdef KEEP_RUNNING
static inline void RangeErrorDetected(void) { /* Do nothing, error is already reported. */ }
#else
static inline void RangeErrorDetected(void) { exit(1); }
#endif

/* Type support code. */
int EnumTypePrint(AmigoEnum value, char *dest, int start, int end) {
    int last = end - 1;
    const char *lit_name = enum_names[value];
    while (start < last && *lit_name) {
        dest[start++] = *lit_name;
        lit_name++;
    }
    dest[start] = '\0';
    return start;
}

static void Amigo_InfoEvent(Amigo_Event_ event, BoolType pre);
static void Amigo_AssignInputVariables();


/** Event names. */
const char *Amigo_event_names[] = {
    "initial-step",                  /**< Initial step. */
    "delay-step",                    /**< Delay step. */
    "tau",                           /**< Tau step. */
    "goto_phase2",                   /**< Event goto_phase2. */
    "arm_left_idle",                 /**< Event arm_left_idle. */
    "arm_left_move",                 /**< Event arm_left_move. */
    "arm_left_plan",                 /**< Event arm_left_plan. */
    "arm_left_replan",               /**< Event arm_left_replan. */
    "arm_left_plan_to_grab",         /**< Event arm_left_plan_to_grab. */
    "arm_left_grab",                 /**< Event arm_left_grab. */
    "arm_right_idle",                /**< Event arm_right_idle. */
    "arm_right_move",                /**< Event arm_right_move. */
    "arm_right_plan",                /**< Event arm_right_plan. */
    "arm_right_replan",              /**< Event arm_right_replan. */
    "arm_right_plan_to_grab",        /**< Event arm_right_plan_to_grab. */
    "arm_right_grab",                /**< Event arm_right_grab. */
    "base_idle",                     /**< Event base_idle. */
    "base_move",                     /**< Event base_move. */
    "base_plan",                     /**< Event base_plan. */
    "grab_skill_grab",               /**< Event grab_skill_grab. */
    "grab_skill_determine_grab_arm", /**< Event grab_skill_determine_grab_arm. */
    "left_grab_exec_check_in_WS",    /**< Event left_grab_exec_check_in_WS. */
    "left_grab_exec_start",          /**< Event left_grab_exec_start. */
    "left_grab_exec_complete",       /**< Event left_grab_exec_complete. */
    "left_grab_exec_idle",           /**< Event left_grab_exec_idle. */
    "navigation_skill_move_to",      /**< Event navigation_skill_move_to. */
    "right_grab_exec_check_in_WS",   /**< Event right_grab_exec_check_in_WS. */
    "right_grab_exec_start",         /**< Event right_grab_exec_start. */
    "right_grab_exec_complete",      /**< Event right_grab_exec_complete. */
    "right_grab_exec_idle",          /**< Event right_grab_exec_idle. */
    "task_waiting",                  /**< Event task_waiting. */
};

/** Enumeration names. */
const char *enum_names[] = {
    "completing",
    "grabbing",
    "idle",
    "idling",
    "moving",
    "moving_to",
    "phase1",
    "phase2",
    "planning",
    "planning_to_grab",
    "replanning",
    "starting",
    "wait",
    "X",
};

/* Constants. */


/* Functions. */


/* Input variables. */
IntType arm_left_plan_viable_;         /**< Input variable "int[0..2] arm_left.plan_viable". */
BoolType arm_left_collision_on_path_;  /**< Input variable "bool arm_left.collision_on_path". */
BoolType arm_left_moving_arm_;         /**< Input variable "bool arm_left.moving_arm". */
BoolType arm_left_goal_reached_;       /**< Input variable "bool arm_left.goal_reached". */
BoolType arm_left_object_in_arm_;      /**< Input variable "bool arm_left.object_in_arm". */
IntType arm_right_plan_viable_;        /**< Input variable "int[0..2] arm_right.plan_viable". */
BoolType arm_right_collision_on_path_; /**< Input variable "bool arm_right.collision_on_path". */
BoolType arm_right_moving_arm_;        /**< Input variable "bool arm_right.moving_arm". */
BoolType arm_right_goal_reached_;      /**< Input variable "bool arm_right.goal_reached". */
BoolType arm_right_object_in_arm_;     /**< Input variable "bool arm_right.object_in_arm". */
IntType base_plan_viable_;             /**< Input variable "int[0..2] base.plan_viable". */
BoolType base_collision_on_path_;      /**< Input variable "bool base.collision_on_path". */
BoolType base_moving_base_;            /**< Input variable "bool base.moving_base". */
BoolType base_goal_reached_;           /**< Input variable "bool base.goal_reached". */
IntType grab_skill_use_arm_;           /**< Input variable "int[0..2] grab_skill.use_arm". */
IntType left_grab_exec_object_in_WS_;  /**< Input variable "int[0..2] left_grab_exec.object_in_WS". */
IntType right_grab_exec_object_in_WS_; /**< Input variable "int[0..2] right_grab_exec.object_in_WS". */
BoolType task_object_grabbed_;         /**< Input variable "bool task.object_grabbed". */

/* State variables. */
AmigoEnum arm_left_;              /**< Discrete variable "E arm_left". */
AmigoEnum arm_right_;             /**< Discrete variable "E arm_right". */
AmigoEnum base_;                  /**< Discrete variable "E base". */
AmigoEnum grab_skill_;            /**< Discrete variable "E grab_skill". */
AmigoEnum left_grab_exec_;        /**< Discrete variable "E left_grab_exec". */
AmigoEnum navigation_skill_;      /**< Discrete variable "E navigation_skill". */
AmigoEnum requirement_arm_left_;  /**< Discrete variable "E requirement_arm_left". */
AmigoEnum requirement_arm_right_; /**< Discrete variable "E requirement_arm_right". */
AmigoEnum right_grab_exec_;       /**< Discrete variable "E right_grab_exec". */
AmigoEnum SafeBaseMovement_;      /**< Discrete variable "E SafeBaseMovement". */
AmigoEnum sup_;                   /**< Discrete variable "E sup". */
BoolType task_navigating_;        /**< Discrete variable "bool task.navigating". */
BoolType task_grabbing_;          /**< Discrete variable "bool task.grabbing". */
AmigoEnum task_;                  /**< Discrete variable "E task". */

RealType model_time; /**< Current model time. */

/** Initialize constants. */
static void InitConstants(void) {

}

/** Print function. */
#if PRINT_OUTPUT
static void PrintOutput(Amigo_Event_ event, BoolType pre) {
}
#endif

/* Event execution code. */

/**
 * Execute code for event "arm_left.grab".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent0(void) {
    BoolType guard = ((((arm_left_) == (_Amigo_planning_to_grab)) || ((arm_left_) == (_Amigo_replanning))) && (((requirement_arm_left_) == (_Amigo_X)) && ((arm_left_plan_viable_) == (1)))) && ((!(arm_left_collision_on_path_)) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_grab_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_planning_to_grab)) {
        arm_left_ = _Amigo_grabbing;
    } else if ((arm_left_) == (_Amigo_replanning)) {
        arm_left_ = _Amigo_grabbing;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_grab_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_left.idle".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent1(void) {
    BoolType guard = (((((arm_left_) == (_Amigo_planning)) || ((arm_left_) == (_Amigo_planning_to_grab))) || (((arm_left_) == (_Amigo_replanning)) || ((((arm_left_) == (_Amigo_moving)) && ((arm_left_goal_reached_) || ((arm_left_moving_arm_) != (TRUE)))) || (((arm_left_) == (_Amigo_grabbing)) && ((arm_left_object_in_arm_) || ((arm_left_moving_arm_) != (TRUE))))))) && ((requirement_arm_left_) == (_Amigo_X))) && ((((arm_left_plan_viable_) == (2)) || ((arm_left_goal_reached_) || (((arm_left_) == (_Amigo_moving)) && ((arm_left_moving_arm_) == (FALSE))))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_idle_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_planning)) {
        arm_left_ = _Amigo_idling;
    } else if ((arm_left_) == (_Amigo_planning_to_grab)) {
        arm_left_ = _Amigo_idling;
    } else if ((arm_left_) == (_Amigo_replanning)) {
        arm_left_ = _Amigo_idling;
    } else if (((arm_left_) == (_Amigo_moving)) && ((arm_left_goal_reached_) || ((arm_left_moving_arm_) != (TRUE)))) {
        arm_left_ = _Amigo_idling;
    } else if (((arm_left_) == (_Amigo_grabbing)) && ((arm_left_object_in_arm_) || ((arm_left_moving_arm_) != (TRUE)))) {
        arm_left_ = _Amigo_idling;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_idle_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_left.move".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent2(void) {
    BoolType guard = ((((arm_left_) == (_Amigo_planning)) || ((arm_left_) == (_Amigo_replanning))) && (((requirement_arm_left_) == (_Amigo_X)) && ((arm_left_plan_viable_) == (1)))) && ((!(arm_left_collision_on_path_)) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_move_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_planning)) {
        arm_left_ = _Amigo_moving;
    } else if ((arm_left_) == (_Amigo_replanning)) {
        arm_left_ = _Amigo_moving;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_move_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_left.plan".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent3(void) {
    BoolType guard = ((((arm_left_) == (_Amigo_idling)) || ((arm_left_) == (_Amigo_grabbing))) && (((left_grab_exec_) == (_Amigo_starting)) && ((left_grab_exec_object_in_WS_) == (1)))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_plan_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_idling)) {
        arm_left_ = _Amigo_planning;
    } else if ((arm_left_) == (_Amigo_grabbing)) {
        arm_left_ = _Amigo_planning;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_plan_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_left.plan_to_grab".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent4(void) {
    BoolType guard = ((((arm_left_) == (_Amigo_idling)) || ((arm_left_) == (_Amigo_moving))) && (((left_grab_exec_) == (_Amigo_starting)) && ((left_grab_exec_object_in_WS_) == (2)))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_plan_to_grab_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_idling)) {
        arm_left_ = _Amigo_planning_to_grab;
    } else if ((arm_left_) == (_Amigo_moving)) {
        arm_left_ = _Amigo_planning_to_grab;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_plan_to_grab_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_left.replan".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent5(void) {
    BoolType guard = ((((arm_left_) == (_Amigo_moving)) || ((arm_left_) == (_Amigo_grabbing))) && ((requirement_arm_left_) == (_Amigo_X))) && (((arm_left_collision_on_path_) || ((arm_left_plan_viable_) != (1))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_replan_, TRUE);
    #endif

    if ((arm_left_) == (_Amigo_moving)) {
        arm_left_ = _Amigo_replanning;
    } else if ((arm_left_) == (_Amigo_grabbing)) {
        arm_left_ = _Amigo_replanning;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_left_replan_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.grab".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent6(void) {
    BoolType guard = ((((arm_right_) == (_Amigo_planning_to_grab)) || ((arm_right_) == (_Amigo_replanning))) && (((requirement_arm_right_) == (_Amigo_X)) && ((arm_right_plan_viable_) == (1)))) && ((!(arm_right_collision_on_path_)) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_grab_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_planning_to_grab)) {
        arm_right_ = _Amigo_grabbing;
    } else if ((arm_right_) == (_Amigo_replanning)) {
        arm_right_ = _Amigo_grabbing;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_grab_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.idle".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent7(void) {
    BoolType guard = (((((arm_right_) == (_Amigo_planning)) || ((arm_right_) == (_Amigo_planning_to_grab))) || (((arm_right_) == (_Amigo_replanning)) || ((((arm_right_) == (_Amigo_moving)) && ((arm_right_goal_reached_) || ((arm_right_moving_arm_) != (TRUE)))) || (((arm_right_) == (_Amigo_grabbing)) && ((arm_right_object_in_arm_) || ((arm_right_moving_arm_) != (TRUE))))))) && ((requirement_arm_right_) == (_Amigo_X))) && ((((arm_right_plan_viable_) == (2)) || ((arm_right_goal_reached_) || (((arm_right_) == (_Amigo_moving)) && ((arm_right_moving_arm_) == (FALSE))))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_idle_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_planning)) {
        arm_right_ = _Amigo_idling;
    } else if ((arm_right_) == (_Amigo_planning_to_grab)) {
        arm_right_ = _Amigo_idling;
    } else if ((arm_right_) == (_Amigo_replanning)) {
        arm_right_ = _Amigo_idling;
    } else if (((arm_right_) == (_Amigo_moving)) && ((arm_right_goal_reached_) || ((arm_right_moving_arm_) != (TRUE)))) {
        arm_right_ = _Amigo_idling;
    } else if (((arm_right_) == (_Amigo_grabbing)) && ((arm_right_object_in_arm_) || ((arm_right_moving_arm_) != (TRUE)))) {
        arm_right_ = _Amigo_idling;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_idle_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.move".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent8(void) {
    BoolType guard = ((((arm_right_) == (_Amigo_planning)) || ((arm_right_) == (_Amigo_replanning))) && (((requirement_arm_right_) == (_Amigo_X)) && ((arm_right_plan_viable_) == (1)))) && ((!(arm_right_collision_on_path_)) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_move_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_planning)) {
        arm_right_ = _Amigo_moving;
    } else if ((arm_right_) == (_Amigo_replanning)) {
        arm_right_ = _Amigo_moving;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_move_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.plan".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent9(void) {
    BoolType guard = ((((arm_right_) == (_Amigo_idling)) || ((arm_right_) == (_Amigo_grabbing))) && (((right_grab_exec_) == (_Amigo_starting)) && ((right_grab_exec_object_in_WS_) == (1)))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_plan_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_idling)) {
        arm_right_ = _Amigo_planning;
    } else if ((arm_right_) == (_Amigo_grabbing)) {
        arm_right_ = _Amigo_planning;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_plan_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.plan_to_grab".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent10(void) {
    BoolType guard = ((((arm_right_) == (_Amigo_idling)) || ((arm_right_) == (_Amigo_moving))) && (((right_grab_exec_) == (_Amigo_starting)) && ((right_grab_exec_object_in_WS_) == (2)))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_plan_to_grab_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_idling)) {
        arm_right_ = _Amigo_planning_to_grab;
    } else if ((arm_right_) == (_Amigo_moving)) {
        arm_right_ = _Amigo_planning_to_grab;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_plan_to_grab_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "arm_right.replan".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent11(void) {
    BoolType guard = ((((arm_right_) == (_Amigo_moving)) || ((arm_right_) == (_Amigo_grabbing))) && ((requirement_arm_right_) == (_Amigo_X))) && (((arm_right_collision_on_path_) || ((arm_right_plan_viable_) != (1))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_replan_, TRUE);
    #endif

    if ((arm_right_) == (_Amigo_moving)) {
        arm_right_ = _Amigo_replanning;
    } else if ((arm_right_) == (_Amigo_grabbing)) {
        arm_right_ = _Amigo_replanning;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(arm_right_replan_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "base.idle".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent12(void) {
    BoolType guard = (((((base_) == (_Amigo_planning)) && ((base_plan_viable_) == (2))) || (((base_) == (_Amigo_moving)) && ((base_goal_reached_) || ((base_moving_base_) != (TRUE))))) && ((SafeBaseMovement_) == (_Amigo_X))) && ((((base_plan_viable_) == (2)) || ((base_goal_reached_) || (((base_) == (_Amigo_moving)) && ((base_moving_base_) == (FALSE))))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_idle_, TRUE);
    #endif

    if (((base_) == (_Amigo_planning)) && ((base_plan_viable_) == (2))) {
        base_ = _Amigo_idling;
    } else if (((base_) == (_Amigo_moving)) && ((base_goal_reached_) || ((base_moving_base_) != (TRUE)))) {
        base_ = _Amigo_idling;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_idle_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "base.move".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent13(void) {
    BoolType guard = (((base_) == (_Amigo_planning)) && (((SafeBaseMovement_) == (_Amigo_X)) && ((base_plan_viable_) == (1)))) && ((!(base_collision_on_path_)) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_move_, TRUE);
    #endif

    base_ = _Amigo_moving;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_move_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "base.plan".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent14(void) {
    BoolType guard = ((((base_) == (_Amigo_idling)) || (((base_) == (_Amigo_moving)) && ((base_plan_viable_) != (1)))) && (((navigation_skill_) == (_Amigo_moving_to)) && ((SafeBaseMovement_) == (_Amigo_X)))) && (((base_collision_on_path_) || ((base_plan_viable_) != (1))) && ((sup_) == (_Amigo_X)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_plan_, TRUE);
    #endif

    if ((base_) == (_Amigo_idling)) {
        base_ = _Amigo_planning;
    } else if (((base_) == (_Amigo_moving)) && ((base_plan_viable_) != (1))) {
        base_ = _Amigo_planning;
    }
    navigation_skill_ = _Amigo_idle;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(base_plan_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "goto_phase2".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent15(void) {
    BoolType guard = ((sup_) == (_Amigo_X)) && (((task_) == (_Amigo_wait)) && ((task_object_grabbed_) == (TRUE)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(goto_phase2_, TRUE);
    #endif

    task_ = _Amigo_phase2;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(goto_phase2_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "grab_skill.determine_grab_arm".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent16(void) {
    BoolType guard = (((grab_skill_) == (_Amigo_grabbing)) && ((grab_skill_use_arm_) == (0))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(grab_skill_determine_grab_arm_, TRUE);
    #endif

    #if EVENT_OUTPUT
        Amigo_InfoEvent(grab_skill_determine_grab_arm_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "grab_skill.grab".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent17(void) {
    BoolType guard = (((grab_skill_) == (_Amigo_idling)) && ((sup_) == (_Amigo_X))) && (((task_) == (_Amigo_phase1)) && ((task_grabbing_) == (FALSE)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(grab_skill_grab_, TRUE);
    #endif

    grab_skill_ = _Amigo_grabbing;
    task_grabbing_ = TRUE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(grab_skill_grab_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "left_grab_exec.check_in_WS".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent18(void) {
    BoolType guard = (((left_grab_exec_) == (_Amigo_starting)) && ((left_grab_exec_object_in_WS_) == (0))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_check_in_WS_, TRUE);
    #endif

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_check_in_WS_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "left_grab_exec.complete".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent19(void) {
    BoolType guard = (((left_grab_exec_) == (_Amigo_starting)) && (arm_left_object_in_arm_)) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_complete_, TRUE);
    #endif

    left_grab_exec_ = _Amigo_completing;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_complete_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "left_grab_exec.idle".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent20(void) {
    BoolType guard = ((left_grab_exec_) == (_Amigo_completing)) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_idle_, TRUE);
    #endif

    left_grab_exec_ = _Amigo_idling;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_idle_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "left_grab_exec.start".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent21(void) {
    BoolType guard = ((((grab_skill_) == (_Amigo_grabbing)) && ((grab_skill_use_arm_) == (1))) && ((left_grab_exec_) == (_Amigo_idling))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_start_, TRUE);
    #endif

    grab_skill_ = _Amigo_idling;
    left_grab_exec_ = _Amigo_starting;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(left_grab_exec_start_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "navigation_skill.move_to".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent22(void) {
    BoolType guard = (((navigation_skill_) == (_Amigo_idle)) && ((sup_) == (_Amigo_X))) && ((((task_) == (_Amigo_phase1)) && ((task_navigating_) == (FALSE))) || ((task_) == (_Amigo_phase2)));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(navigation_skill_move_to_, TRUE);
    #endif

    navigation_skill_ = _Amigo_moving_to;
    if (((task_) == (_Amigo_phase1)) && ((task_navigating_) == (FALSE))) {
        task_navigating_ = TRUE;
    } else if ((task_) == (_Amigo_phase2)) {
        task_ = _Amigo_phase2;
    }

    #if EVENT_OUTPUT
        Amigo_InfoEvent(navigation_skill_move_to_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "right_grab_exec.check_in_WS".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent23(void) {
    BoolType guard = (((right_grab_exec_) == (_Amigo_starting)) && ((right_grab_exec_object_in_WS_) == (0))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_check_in_WS_, TRUE);
    #endif

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_check_in_WS_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "right_grab_exec.complete".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent24(void) {
    BoolType guard = (((right_grab_exec_) == (_Amigo_starting)) && (arm_right_object_in_arm_)) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_complete_, TRUE);
    #endif

    right_grab_exec_ = _Amigo_completing;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_complete_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "right_grab_exec.idle".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent25(void) {
    BoolType guard = ((right_grab_exec_) == (_Amigo_completing)) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_idle_, TRUE);
    #endif

    right_grab_exec_ = _Amigo_idling;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_idle_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "right_grab_exec.start".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent26(void) {
    BoolType guard = ((((grab_skill_) == (_Amigo_grabbing)) && ((grab_skill_use_arm_) == (2))) && ((right_grab_exec_) == (_Amigo_idling))) && ((sup_) == (_Amigo_X));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_start_, TRUE);
    #endif

    grab_skill_ = _Amigo_idling;
    right_grab_exec_ = _Amigo_starting;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(right_grab_exec_start_, FALSE);
    #endif
    return TRUE;
}

/**
 * Execute code for event "task.waiting".
 *
 * @return Whether the event was performed.
 */
static BoolType execEvent27(void) {
    BoolType guard = ((sup_) == (_Amigo_X)) && (((task_) == (_Amigo_phase1)) && (((task_navigating_) == (TRUE)) && ((task_grabbing_) == (TRUE))));
    if (!guard) return FALSE;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(task_waiting_, TRUE);
    #endif

    task_ = _Amigo_wait;

    #if EVENT_OUTPUT
        Amigo_InfoEvent(task_waiting_, FALSE);
    #endif
    return TRUE;
}

/**
 * Normalize and check the new value of a continuous variable after an update.
 * @param new_value Unnormalized new value of the continuous variable.
 * @param var_name Name of the continuous variabl ein the CIF model.
 * @return The normalized new value of the continuous variable.
 */
static inline RealType UpdateContValue(RealType new_value, const char *var_name) {
    if (isfinite(new_value)) {
        return (new_value == -0.0) ? 0.0 : new_value;
    }

    const char *err_type;
    if (isnan(new_value)) {
        err_type = "NaN";
    } else if (new_value > 0) {
        err_type = "+inf";
    } else {
        err_type = "-inf";
    }
    fprintf(stderr, "Continuous variable \"%s\" has become %s.\n", var_name, err_type);

#ifdef KEEP_RUNNING
    return 0.0;
#else
    exit(1);
#endif
}

/** Repeatedly perform discrete event steps, until no progress can be made any more. */
static void PerformEvents(void) {
    int count = 0;
    for (;;) {
        count++;
        if (count > MAX_NUM_EVENTS) { /* 'Infinite' loop detection. */
            fprintf(stderr, "Warning: Quitting after performing %d events, infinite loop?\n", count);
            break;
        }

        if (execEvent0()) continue;  /* (Try to) perform event "arm_left.grab". */
        if (execEvent1()) continue;  /* (Try to) perform event "arm_left.idle". */
        if (execEvent2()) continue;  /* (Try to) perform event "arm_left.move". */
        if (execEvent3()) continue;  /* (Try to) perform event "arm_left.plan". */
        if (execEvent4()) continue;  /* (Try to) perform event "arm_left.plan_to_grab". */
        if (execEvent5()) continue;  /* (Try to) perform event "arm_left.replan". */
        if (execEvent6()) continue;  /* (Try to) perform event "arm_right.grab". */
        if (execEvent7()) continue;  /* (Try to) perform event "arm_right.idle". */
        if (execEvent8()) continue;  /* (Try to) perform event "arm_right.move". */
        if (execEvent9()) continue;  /* (Try to) perform event "arm_right.plan". */
        if (execEvent10()) continue;  /* (Try to) perform event "arm_right.plan_to_grab". */
        if (execEvent11()) continue;  /* (Try to) perform event "arm_right.replan". */
        if (execEvent12()) continue;  /* (Try to) perform event "base.idle". */
        if (execEvent13()) continue;  /* (Try to) perform event "base.move". */
        if (execEvent14()) continue;  /* (Try to) perform event "base.plan". */
        if (execEvent15()) continue;  /* (Try to) perform event "goto_phase2". */
        if (execEvent16()) continue;  /* (Try to) perform event "grab_skill.determine_grab_arm". */
        if (execEvent17()) continue;  /* (Try to) perform event "grab_skill.grab". */
        if (execEvent18()) continue;  /* (Try to) perform event "left_grab_exec.check_in_WS". */
        if (execEvent19()) continue;  /* (Try to) perform event "left_grab_exec.complete". */
        if (execEvent20()) continue;  /* (Try to) perform event "left_grab_exec.idle". */
        if (execEvent21()) continue;  /* (Try to) perform event "left_grab_exec.start". */
        if (execEvent22()) continue;  /* (Try to) perform event "navigation_skill.move_to". */
        if (execEvent23()) continue;  /* (Try to) perform event "right_grab_exec.check_in_WS". */
        if (execEvent24()) continue;  /* (Try to) perform event "right_grab_exec.complete". */
        if (execEvent25()) continue;  /* (Try to) perform event "right_grab_exec.idle". */
        if (execEvent26()) continue;  /* (Try to) perform event "right_grab_exec.start". */
        if (execEvent27()) continue;  /* (Try to) perform event "task.waiting". */
        break; /* No event fired, done with discrete steps. */
    }
}

/** First model call, initializing, and performing discrete events before the first time step. */
void Amigo_EngineFirstStep(void) {
    InitConstants();

    model_time = 0.0;
    Amigo_AssignInputVariables();
    arm_left_ = _Amigo_idling;
    arm_right_ = _Amigo_idling;
    base_ = _Amigo_idling;
    grab_skill_ = _Amigo_idling;
    left_grab_exec_ = _Amigo_idling;
    navigation_skill_ = _Amigo_idle;
    requirement_arm_left_ = _Amigo_X;
    requirement_arm_right_ = _Amigo_X;
    right_grab_exec_ = _Amigo_idling;
    SafeBaseMovement_ = _Amigo_X;
    sup_ = _Amigo_X;
    task_navigating_ = FALSE;
    task_grabbing_ = FALSE;
    task_ = _Amigo_phase1;

    #if PRINT_OUTPUT
        /* pre-initial and post-initial prints. */
        PrintOutput(EVT_INITIAL_, TRUE);
        PrintOutput(EVT_INITIAL_, FALSE);
    #endif

    PerformEvents();

    #if PRINT_OUTPUT
        /* pre-timestep print. */
        PrintOutput(EVT_DELAY_, TRUE);
    #endif
}

/**
 * Engine takes a time step of length \a delta.
 * @param delta Length of the time step.
 */
void Amigo_EngineTimeStep(double delta) {
    Amigo_AssignInputVariables();

    /* Update continuous variables. */
    if (delta > 0.0) {

        model_time += delta;
    }

    #if PRINT_OUTPUT
        /* post-timestep print. */
        PrintOutput(EVT_DELAY_, FALSE);
    #endif

    PerformEvents();

    #if PRINT_OUTPUT
        /* pre-timestep print. */
        PrintOutput(EVT_DELAY_, TRUE);
    #endif
}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 3), // int()(enum EnumAmigo_, char *, int, int)
/*  1 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // enum EnumAmigo_
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 17), // char *
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 21), // void()(double)
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 21), // void()(enum AmigoEventEnum_, _Bool)
/* 10 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum AmigoEventEnum_
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 21), // void()(void)
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 17), // char const *
/* 16 */ _CFFI_OP(_CFFI_OP_OPEN_ARRAY, 15), // char const *[]
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 18 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21), // int32_t
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // void(*)(enum AmigoEventEnum_, _Bool)
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 13), // void(*)(void)
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_EVT_INITIAL_(unsigned long long *o)
{
  int n = (EVT_INITIAL_) <= 0;
  *o = (unsigned long long)((EVT_INITIAL_) | 0);  /* check that EVT_INITIAL_ is an integer */
  return n;
}

static int _cffi_const_EVT_DELAY_(unsigned long long *o)
{
  int n = (EVT_DELAY_) <= 0;
  *o = (unsigned long long)((EVT_DELAY_) | 0);  /* check that EVT_DELAY_ is an integer */
  return n;
}

static int _cffi_const_EVT_TAU_(unsigned long long *o)
{
  int n = (EVT_TAU_) <= 0;
  *o = (unsigned long long)((EVT_TAU_) | 0);  /* check that EVT_TAU_ is an integer */
  return n;
}

static int _cffi_const_goto_phase2_(unsigned long long *o)
{
  int n = (goto_phase2_) <= 0;
  *o = (unsigned long long)((goto_phase2_) | 0);  /* check that goto_phase2_ is an integer */
  return n;
}

static int _cffi_const_arm_left_idle_(unsigned long long *o)
{
  int n = (arm_left_idle_) <= 0;
  *o = (unsigned long long)((arm_left_idle_) | 0);  /* check that arm_left_idle_ is an integer */
  return n;
}

static int _cffi_const_arm_left_move_(unsigned long long *o)
{
  int n = (arm_left_move_) <= 0;
  *o = (unsigned long long)((arm_left_move_) | 0);  /* check that arm_left_move_ is an integer */
  return n;
}

static int _cffi_const_arm_left_plan_(unsigned long long *o)
{
  int n = (arm_left_plan_) <= 0;
  *o = (unsigned long long)((arm_left_plan_) | 0);  /* check that arm_left_plan_ is an integer */
  return n;
}

static int _cffi_const_arm_left_replan_(unsigned long long *o)
{
  int n = (arm_left_replan_) <= 0;
  *o = (unsigned long long)((arm_left_replan_) | 0);  /* check that arm_left_replan_ is an integer */
  return n;
}

static int _cffi_const_arm_left_plan_to_grab_(unsigned long long *o)
{
  int n = (arm_left_plan_to_grab_) <= 0;
  *o = (unsigned long long)((arm_left_plan_to_grab_) | 0);  /* check that arm_left_plan_to_grab_ is an integer */
  return n;
}

static int _cffi_const_arm_left_grab_(unsigned long long *o)
{
  int n = (arm_left_grab_) <= 0;
  *o = (unsigned long long)((arm_left_grab_) | 0);  /* check that arm_left_grab_ is an integer */
  return n;
}

static int _cffi_const_arm_right_idle_(unsigned long long *o)
{
  int n = (arm_right_idle_) <= 0;
  *o = (unsigned long long)((arm_right_idle_) | 0);  /* check that arm_right_idle_ is an integer */
  return n;
}

static int _cffi_const_arm_right_move_(unsigned long long *o)
{
  int n = (arm_right_move_) <= 0;
  *o = (unsigned long long)((arm_right_move_) | 0);  /* check that arm_right_move_ is an integer */
  return n;
}

static int _cffi_const_arm_right_plan_(unsigned long long *o)
{
  int n = (arm_right_plan_) <= 0;
  *o = (unsigned long long)((arm_right_plan_) | 0);  /* check that arm_right_plan_ is an integer */
  return n;
}

static int _cffi_const_arm_right_replan_(unsigned long long *o)
{
  int n = (arm_right_replan_) <= 0;
  *o = (unsigned long long)((arm_right_replan_) | 0);  /* check that arm_right_replan_ is an integer */
  return n;
}

static int _cffi_const_arm_right_plan_to_grab_(unsigned long long *o)
{
  int n = (arm_right_plan_to_grab_) <= 0;
  *o = (unsigned long long)((arm_right_plan_to_grab_) | 0);  /* check that arm_right_plan_to_grab_ is an integer */
  return n;
}

static int _cffi_const_arm_right_grab_(unsigned long long *o)
{
  int n = (arm_right_grab_) <= 0;
  *o = (unsigned long long)((arm_right_grab_) | 0);  /* check that arm_right_grab_ is an integer */
  return n;
}

static int _cffi_const_base_idle_(unsigned long long *o)
{
  int n = (base_idle_) <= 0;
  *o = (unsigned long long)((base_idle_) | 0);  /* check that base_idle_ is an integer */
  return n;
}

static int _cffi_const_base_move_(unsigned long long *o)
{
  int n = (base_move_) <= 0;
  *o = (unsigned long long)((base_move_) | 0);  /* check that base_move_ is an integer */
  return n;
}

static int _cffi_const_base_plan_(unsigned long long *o)
{
  int n = (base_plan_) <= 0;
  *o = (unsigned long long)((base_plan_) | 0);  /* check that base_plan_ is an integer */
  return n;
}

static int _cffi_const_grab_skill_grab_(unsigned long long *o)
{
  int n = (grab_skill_grab_) <= 0;
  *o = (unsigned long long)((grab_skill_grab_) | 0);  /* check that grab_skill_grab_ is an integer */
  return n;
}

static int _cffi_const_grab_skill_determine_grab_arm_(unsigned long long *o)
{
  int n = (grab_skill_determine_grab_arm_) <= 0;
  *o = (unsigned long long)((grab_skill_determine_grab_arm_) | 0);  /* check that grab_skill_determine_grab_arm_ is an integer */
  return n;
}

static int _cffi_const_left_grab_exec_check_in_WS_(unsigned long long *o)
{
  int n = (left_grab_exec_check_in_WS_) <= 0;
  *o = (unsigned long long)((left_grab_exec_check_in_WS_) | 0);  /* check that left_grab_exec_check_in_WS_ is an integer */
  return n;
}

static int _cffi_const_left_grab_exec_start_(unsigned long long *o)
{
  int n = (left_grab_exec_start_) <= 0;
  *o = (unsigned long long)((left_grab_exec_start_) | 0);  /* check that left_grab_exec_start_ is an integer */
  return n;
}

static int _cffi_const_left_grab_exec_complete_(unsigned long long *o)
{
  int n = (left_grab_exec_complete_) <= 0;
  *o = (unsigned long long)((left_grab_exec_complete_) | 0);  /* check that left_grab_exec_complete_ is an integer */
  return n;
}

static int _cffi_const_left_grab_exec_idle_(unsigned long long *o)
{
  int n = (left_grab_exec_idle_) <= 0;
  *o = (unsigned long long)((left_grab_exec_idle_) | 0);  /* check that left_grab_exec_idle_ is an integer */
  return n;
}

static int _cffi_const_navigation_skill_move_to_(unsigned long long *o)
{
  int n = (navigation_skill_move_to_) <= 0;
  *o = (unsigned long long)((navigation_skill_move_to_) | 0);  /* check that navigation_skill_move_to_ is an integer */
  return n;
}

static int _cffi_const_right_grab_exec_check_in_WS_(unsigned long long *o)
{
  int n = (right_grab_exec_check_in_WS_) <= 0;
  *o = (unsigned long long)((right_grab_exec_check_in_WS_) | 0);  /* check that right_grab_exec_check_in_WS_ is an integer */
  return n;
}

static int _cffi_const_right_grab_exec_start_(unsigned long long *o)
{
  int n = (right_grab_exec_start_) <= 0;
  *o = (unsigned long long)((right_grab_exec_start_) | 0);  /* check that right_grab_exec_start_ is an integer */
  return n;
}

static int _cffi_const_right_grab_exec_complete_(unsigned long long *o)
{
  int n = (right_grab_exec_complete_) <= 0;
  *o = (unsigned long long)((right_grab_exec_complete_) | 0);  /* check that right_grab_exec_complete_ is an integer */
  return n;
}

static int _cffi_const_right_grab_exec_idle_(unsigned long long *o)
{
  int n = (right_grab_exec_idle_) <= 0;
  *o = (unsigned long long)((right_grab_exec_idle_) | 0);  /* check that right_grab_exec_idle_ is an integer */
  return n;
}

static int _cffi_const_task_waiting_(unsigned long long *o)
{
  int n = (task_waiting_) <= 0;
  *o = (unsigned long long)((task_waiting_) | 0);  /* check that task_waiting_ is an integer */
  return n;
}

static int _cffi_const__Amigo_completing(unsigned long long *o)
{
  int n = (_Amigo_completing) <= 0;
  *o = (unsigned long long)((_Amigo_completing) | 0);  /* check that _Amigo_completing is an integer */
  return n;
}

static int _cffi_const__Amigo_grabbing(unsigned long long *o)
{
  int n = (_Amigo_grabbing) <= 0;
  *o = (unsigned long long)((_Amigo_grabbing) | 0);  /* check that _Amigo_grabbing is an integer */
  return n;
}

static int _cffi_const__Amigo_idle(unsigned long long *o)
{
  int n = (_Amigo_idle) <= 0;
  *o = (unsigned long long)((_Amigo_idle) | 0);  /* check that _Amigo_idle is an integer */
  return n;
}

static int _cffi_const__Amigo_idling(unsigned long long *o)
{
  int n = (_Amigo_idling) <= 0;
  *o = (unsigned long long)((_Amigo_idling) | 0);  /* check that _Amigo_idling is an integer */
  return n;
}

static int _cffi_const__Amigo_moving(unsigned long long *o)
{
  int n = (_Amigo_moving) <= 0;
  *o = (unsigned long long)((_Amigo_moving) | 0);  /* check that _Amigo_moving is an integer */
  return n;
}

static int _cffi_const__Amigo_moving_to(unsigned long long *o)
{
  int n = (_Amigo_moving_to) <= 0;
  *o = (unsigned long long)((_Amigo_moving_to) | 0);  /* check that _Amigo_moving_to is an integer */
  return n;
}

static int _cffi_const__Amigo_phase1(unsigned long long *o)
{
  int n = (_Amigo_phase1) <= 0;
  *o = (unsigned long long)((_Amigo_phase1) | 0);  /* check that _Amigo_phase1 is an integer */
  return n;
}

static int _cffi_const__Amigo_phase2(unsigned long long *o)
{
  int n = (_Amigo_phase2) <= 0;
  *o = (unsigned long long)((_Amigo_phase2) | 0);  /* check that _Amigo_phase2 is an integer */
  return n;
}

static int _cffi_const__Amigo_planning(unsigned long long *o)
{
  int n = (_Amigo_planning) <= 0;
  *o = (unsigned long long)((_Amigo_planning) | 0);  /* check that _Amigo_planning is an integer */
  return n;
}

static int _cffi_const__Amigo_planning_to_grab(unsigned long long *o)
{
  int n = (_Amigo_planning_to_grab) <= 0;
  *o = (unsigned long long)((_Amigo_planning_to_grab) | 0);  /* check that _Amigo_planning_to_grab is an integer */
  return n;
}

static int _cffi_const__Amigo_replanning(unsigned long long *o)
{
  int n = (_Amigo_replanning) <= 0;
  *o = (unsigned long long)((_Amigo_replanning) | 0);  /* check that _Amigo_replanning is an integer */
  return n;
}

static int _cffi_const__Amigo_starting(unsigned long long *o)
{
  int n = (_Amigo_starting) <= 0;
  *o = (unsigned long long)((_Amigo_starting) | 0);  /* check that _Amigo_starting is an integer */
  return n;
}

static int _cffi_const__Amigo_wait(unsigned long long *o)
{
  int n = (_Amigo_wait) <= 0;
  *o = (unsigned long long)((_Amigo_wait) | 0);  /* check that _Amigo_wait is an integer */
  return n;
}

static int _cffi_const__Amigo_X(unsigned long long *o)
{
  int n = (_Amigo_X) <= 0;
  *o = (unsigned long long)((_Amigo_X) | 0);  /* check that _Amigo_X is an integer */
  return n;
}

static struct _cffi_externpy_s _cffi_externpy__Amigo_AssignInputVariables =
  { "_amigo_engine.Amigo_AssignInputVariables", 0 };

static void Amigo_AssignInputVariables(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__Amigo_AssignInputVariables, p);
}

static struct _cffi_externpy_s _cffi_externpy__Amigo_InfoEvent =
  { "_amigo_engine.Amigo_InfoEvent", 0 };

static void Amigo_InfoEvent(enum AmigoEventEnum_ a0, _Bool a1)
{
  char a[16];
  char *p = a;
  *(enum AmigoEventEnum_ *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__Amigo_InfoEvent, p);
}

static void _cffi_d_Amigo_EngineFirstStep(void)
{
  Amigo_EngineFirstStep();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Amigo_EngineFirstStep(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { Amigo_EngineFirstStep(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_Amigo_EngineFirstStep _cffi_d_Amigo_EngineFirstStep
#endif

static void _cffi_d_Amigo_EngineTimeStep(double x0)
{
  Amigo_EngineTimeStep(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Amigo_EngineTimeStep(PyObject *self, PyObject *arg0)
{
  double x0;

  x0 = (double)_cffi_to_c_double(arg0);
  if (x0 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { Amigo_EngineTimeStep(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_Amigo_EngineTimeStep _cffi_d_Amigo_EngineTimeStep
#endif

static int _cffi_d_EnumTypePrint(enum EnumAmigo_ x0, char * x1, int x2, int x3)
{
  return EnumTypePrint(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_EnumTypePrint(PyObject *self, PyObject *args)
{
  enum EnumAmigo_ x0;
  char * x1;
  int x2;
  int x3;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "EnumTypePrint", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(2), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = EnumTypePrint(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_EnumTypePrint _cffi_d_EnumTypePrint
#endif

static char const * *_cffi_var_Amigo_event_names(void)
{
  return (Amigo_event_names);
}

static enum EnumAmigo_ *_cffi_var_SafeBaseMovement_(void)
{
  return &(SafeBaseMovement_);
}

static enum EnumAmigo_ *_cffi_var_arm_left_(void)
{
  return &(arm_left_);
}

static _Bool *_cffi_var_arm_left_collision_on_path_(void)
{
  return &(arm_left_collision_on_path_);
}

static _Bool *_cffi_var_arm_left_goal_reached_(void)
{
  return &(arm_left_goal_reached_);
}

static _Bool *_cffi_var_arm_left_moving_arm_(void)
{
  return &(arm_left_moving_arm_);
}

static _Bool *_cffi_var_arm_left_object_in_arm_(void)
{
  return &(arm_left_object_in_arm_);
}

static int32_t *_cffi_var_arm_left_plan_viable_(void)
{
  return &(arm_left_plan_viable_);
}

static enum EnumAmigo_ *_cffi_var_arm_right_(void)
{
  return &(arm_right_);
}

static _Bool *_cffi_var_arm_right_collision_on_path_(void)
{
  return &(arm_right_collision_on_path_);
}

static _Bool *_cffi_var_arm_right_goal_reached_(void)
{
  return &(arm_right_goal_reached_);
}

static _Bool *_cffi_var_arm_right_moving_arm_(void)
{
  return &(arm_right_moving_arm_);
}

static _Bool *_cffi_var_arm_right_object_in_arm_(void)
{
  return &(arm_right_object_in_arm_);
}

static int32_t *_cffi_var_arm_right_plan_viable_(void)
{
  return &(arm_right_plan_viable_);
}

static enum EnumAmigo_ *_cffi_var_base_(void)
{
  return &(base_);
}

static _Bool *_cffi_var_base_collision_on_path_(void)
{
  return &(base_collision_on_path_);
}

static _Bool *_cffi_var_base_goal_reached_(void)
{
  return &(base_goal_reached_);
}

static _Bool *_cffi_var_base_moving_base_(void)
{
  return &(base_moving_base_);
}

static int32_t *_cffi_var_base_plan_viable_(void)
{
  return &(base_plan_viable_);
}

static char const * *_cffi_var_enum_names(void)
{
  return (enum_names);
}

static enum EnumAmigo_ *_cffi_var_grab_skill_(void)
{
  return &(grab_skill_);
}

static int32_t *_cffi_var_grab_skill_use_arm_(void)
{
  return &(grab_skill_use_arm_);
}

static enum EnumAmigo_ *_cffi_var_left_grab_exec_(void)
{
  return &(left_grab_exec_);
}

static int32_t *_cffi_var_left_grab_exec_object_in_WS_(void)
{
  return &(left_grab_exec_object_in_WS_);
}

static double *_cffi_var_model_time(void)
{
  return &(model_time);
}

static enum EnumAmigo_ *_cffi_var_navigation_skill_(void)
{
  return &(navigation_skill_);
}

static enum EnumAmigo_ *_cffi_var_requirement_arm_left_(void)
{
  return &(requirement_arm_left_);
}

static enum EnumAmigo_ *_cffi_var_requirement_arm_right_(void)
{
  return &(requirement_arm_right_);
}

static enum EnumAmigo_ *_cffi_var_right_grab_exec_(void)
{
  return &(right_grab_exec_);
}

static int32_t *_cffi_var_right_grab_exec_object_in_WS_(void)
{
  return &(right_grab_exec_object_in_WS_);
}

static enum EnumAmigo_ *_cffi_var_sup_(void)
{
  return &(sup_);
}

static enum EnumAmigo_ *_cffi_var_task_(void)
{
  return &(task_);
}

static _Bool *_cffi_var_task_grabbing_(void)
{
  return &(task_grabbing_);
}

static _Bool *_cffi_var_task_navigating_(void)
{
  return &(task_navigating_);
}

static _Bool *_cffi_var_task_object_grabbed_(void)
{
  return &(task_object_grabbed_);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "Amigo_AssignInputVariables", (void *)&_cffi_externpy__Amigo_AssignInputVariables, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 20), (void *)Amigo_AssignInputVariables },
  { "Amigo_EngineFirstStep", (void *)_cffi_f_Amigo_EngineFirstStep, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 13), (void *)_cffi_d_Amigo_EngineFirstStep },
  { "Amigo_EngineTimeStep", (void *)_cffi_f_Amigo_EngineTimeStep, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 6), (void *)_cffi_d_Amigo_EngineTimeStep },
  { "Amigo_InfoEvent", (void *)&_cffi_externpy__Amigo_InfoEvent, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 19), (void *)Amigo_InfoEvent },
  { "Amigo_event_names", (void *)_cffi_var_Amigo_event_names, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 16), (void *)0 },
  { "EVT_DELAY_", (void *)_cffi_const_EVT_DELAY_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVT_INITIAL_", (void *)_cffi_const_EVT_INITIAL_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVT_TAU_", (void *)_cffi_const_EVT_TAU_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EnumTypePrint", (void *)_cffi_f_EnumTypePrint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_EnumTypePrint },
  { "SafeBaseMovement_", (void *)_cffi_var_SafeBaseMovement_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "_Amigo_X", (void *)_cffi_const__Amigo_X, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_completing", (void *)_cffi_const__Amigo_completing, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_grabbing", (void *)_cffi_const__Amigo_grabbing, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_idle", (void *)_cffi_const__Amigo_idle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_idling", (void *)_cffi_const__Amigo_idling, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_moving", (void *)_cffi_const__Amigo_moving, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_moving_to", (void *)_cffi_const__Amigo_moving_to, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_phase1", (void *)_cffi_const__Amigo_phase1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_phase2", (void *)_cffi_const__Amigo_phase2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_planning", (void *)_cffi_const__Amigo_planning, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_planning_to_grab", (void *)_cffi_const__Amigo_planning_to_grab, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_replanning", (void *)_cffi_const__Amigo_replanning, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_starting", (void *)_cffi_const__Amigo_starting, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "_Amigo_wait", (void *)_cffi_const__Amigo_wait, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_", (void *)_cffi_var_arm_left_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "arm_left_collision_on_path_", (void *)_cffi_var_arm_left_collision_on_path_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_left_goal_reached_", (void *)_cffi_var_arm_left_goal_reached_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_left_grab_", (void *)_cffi_const_arm_left_grab_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_idle_", (void *)_cffi_const_arm_left_idle_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_move_", (void *)_cffi_const_arm_left_move_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_moving_arm_", (void *)_cffi_var_arm_left_moving_arm_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_left_object_in_arm_", (void *)_cffi_var_arm_left_object_in_arm_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_left_plan_", (void *)_cffi_const_arm_left_plan_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_plan_to_grab_", (void *)_cffi_const_arm_left_plan_to_grab_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_left_plan_viable_", (void *)_cffi_var_arm_left_plan_viable_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "arm_left_replan_", (void *)_cffi_const_arm_left_replan_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_", (void *)_cffi_var_arm_right_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "arm_right_collision_on_path_", (void *)_cffi_var_arm_right_collision_on_path_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_right_goal_reached_", (void *)_cffi_var_arm_right_goal_reached_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_right_grab_", (void *)_cffi_const_arm_right_grab_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_idle_", (void *)_cffi_const_arm_right_idle_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_move_", (void *)_cffi_const_arm_right_move_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_moving_arm_", (void *)_cffi_var_arm_right_moving_arm_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_right_object_in_arm_", (void *)_cffi_var_arm_right_object_in_arm_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "arm_right_plan_", (void *)_cffi_const_arm_right_plan_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_plan_to_grab_", (void *)_cffi_const_arm_right_plan_to_grab_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "arm_right_plan_viable_", (void *)_cffi_var_arm_right_plan_viable_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "arm_right_replan_", (void *)_cffi_const_arm_right_replan_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "base_", (void *)_cffi_var_base_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "base_collision_on_path_", (void *)_cffi_var_base_collision_on_path_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "base_goal_reached_", (void *)_cffi_var_base_goal_reached_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "base_idle_", (void *)_cffi_const_base_idle_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "base_move_", (void *)_cffi_const_base_move_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "base_moving_base_", (void *)_cffi_var_base_moving_base_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "base_plan_", (void *)_cffi_const_base_plan_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "base_plan_viable_", (void *)_cffi_var_base_plan_viable_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "enum_names", (void *)_cffi_var_enum_names, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 16), (void *)0 },
  { "goto_phase2_", (void *)_cffi_const_goto_phase2_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "grab_skill_", (void *)_cffi_var_grab_skill_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "grab_skill_determine_grab_arm_", (void *)_cffi_const_grab_skill_determine_grab_arm_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "grab_skill_grab_", (void *)_cffi_const_grab_skill_grab_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "grab_skill_use_arm_", (void *)_cffi_var_grab_skill_use_arm_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "left_grab_exec_", (void *)_cffi_var_left_grab_exec_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "left_grab_exec_check_in_WS_", (void *)_cffi_const_left_grab_exec_check_in_WS_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "left_grab_exec_complete_", (void *)_cffi_const_left_grab_exec_complete_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "left_grab_exec_idle_", (void *)_cffi_const_left_grab_exec_idle_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "left_grab_exec_object_in_WS_", (void *)_cffi_var_left_grab_exec_object_in_WS_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "left_grab_exec_start_", (void *)_cffi_const_left_grab_exec_start_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "model_time", (void *)_cffi_var_model_time, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 7), (void *)0 },
  { "navigation_skill_", (void *)_cffi_var_navigation_skill_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "navigation_skill_move_to_", (void *)_cffi_const_navigation_skill_move_to_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "requirement_arm_left_", (void *)_cffi_var_requirement_arm_left_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "requirement_arm_right_", (void *)_cffi_var_requirement_arm_right_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "right_grab_exec_", (void *)_cffi_var_right_grab_exec_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "right_grab_exec_check_in_WS_", (void *)_cffi_const_right_grab_exec_check_in_WS_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "right_grab_exec_complete_", (void *)_cffi_const_right_grab_exec_complete_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "right_grab_exec_idle_", (void *)_cffi_const_right_grab_exec_idle_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "right_grab_exec_object_in_WS_", (void *)_cffi_var_right_grab_exec_object_in_WS_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 18), (void *)0 },
  { "right_grab_exec_start_", (void *)_cffi_const_right_grab_exec_start_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "sup_", (void *)_cffi_var_sup_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "task_", (void *)_cffi_var_task_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 1), (void *)0 },
  { "task_grabbing_", (void *)_cffi_var_task_grabbing_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "task_navigating_", (void *)_cffi_var_task_navigating_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "task_object_grabbed_", (void *)_cffi_var_task_object_grabbed_, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 11), (void *)0 },
  { "task_waiting_", (void *)_cffi_const_task_waiting_, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "AmigoEventEnum_", 10, _cffi_prim_int(sizeof(enum AmigoEventEnum_), ((enum AmigoEventEnum_)-1) <= 0),
    "EVT_INITIAL_,EVT_DELAY_,EVT_TAU_,goto_phase2_,arm_left_idle_,arm_left_move_,arm_left_plan_,arm_left_replan_,arm_left_plan_to_grab_,arm_left_grab_,arm_right_idle_,arm_right_move_,arm_right_plan_,arm_right_replan_,arm_right_plan_to_grab_,arm_right_grab_,base_idle_,base_move_,base_plan_,grab_skill_grab_,grab_skill_determine_grab_arm_,left_grab_exec_check_in_WS_,left_grab_exec_start_,left_grab_exec_complete_,left_grab_exec_idle_,navigation_skill_move_to_,right_grab_exec_check_in_WS_,right_grab_exec_start_,right_grab_exec_complete_,right_grab_exec_idle_,task_waiting_" },
  { "EnumAmigo_", 1, _cffi_prim_int(sizeof(enum EnumAmigo_), ((enum EnumAmigo_)-1) <= 0),
    "_Amigo_completing,_Amigo_grabbing,_Amigo_idle,_Amigo_idling,_Amigo_moving,_Amigo_moving_to,_Amigo_phase1,_Amigo_phase2,_Amigo_planning,_Amigo_planning_to_grab,_Amigo_replanning,_Amigo_starting,_Amigo_wait,_Amigo_X" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "AmigoEnum", 1 },
  { "Amigo_Event_", 10 },
  { "BoolType", 11 },
  { "IntType", 18 },
  { "RealType", 7 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  _cffi_enums,
  _cffi_typenames,
  85,  /* num_globals */
  0,  /* num_struct_unions */
  2,  /* num_enums */
  5,  /* num_typenames */
  NULL,  /* no includes */
  22,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__amigo_engine(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__amigo_engine(void) { return NULL; }
#  else
     init_amigo_engine(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__amigo_engine(void)
{
  return _cffi_init("_amigo_engine", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_amigo_engine(void)
{
  _cffi_init("_amigo_engine", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
